# list
# 1. allows hetrogeneous
# 2. index start from zero
# 3. mutable using index
# 4.[]

sample_list=[2,54,"hi",1-2j, 2.5]
sample_list

In [3]:
type(sample_list)

list

In [4]:
sample_list(2)

TypeError: 'list' object is not callable

In [5]:
sample_list[2]

'hi'

In [6]:
sample_list[10]

IndexError: list index out of range

In [7]:
sample_list[2]=33


In [8]:
sample_list

[2, 54, 33, (1-2j), 2.5]

In [9]:
sample_list[3]
sample_list


[2, 54, 33, (1-2j), 2.5]

In [10]:
sample_list.sort


<function list.sort(*, key=None, reverse=False)>

In [11]:
sample_list.sort()

TypeError: '<' not supported between instances of 'complex' and 'int'

In [12]:
sample_list[3]=22
sample_list


[2, 33, 54, 22, 2.5]

In [13]:
sample_list.sort()

In [14]:
sample_list


[2, 2.5, 22, 33, 54]

In [15]:
sample_list.reverse()

In [19]:
sample_list

[54, 33, 22, 2.5, 2]

# Tuple
# 1. Allows heterogenous
# 2. Index starts from 0 and retrieve using index
# 3. Cannot change the data once declared - immutable
# 4. ()

In [20]:
sample_tuple=(2,4,5.5,"hi",1-2j)
sample_tuple

(2, 4, 5.5, 'hi', (1-2j))

In [21]:
type(sample_tuple)

tuple

In [22]:
sample_tuple[2]

5.5

In [23]:
sample_tuple[2]=2.2

TypeError: 'tuple' object does not support item assignment

In [24]:
sample_tuple.reverse()
sample_tuple

AttributeError: 'tuple' object has no attribute 'reverse'

In [25]:
sample_tuple

(2, 4, 5.5, 'hi', (1-2j))

In [26]:
sample_tuple.reverse()


AttributeError: 'tuple' object has no attribute 'reverse'

In [27]:
list(sample_tuple)

[2, 4, 5.5, 'hi', (1-2j)]

In [28]:
sample_tuple.reverse()

AttributeError: 'tuple' object has no attribute 'reverse'

In [29]:
a=list(sample_tuple)
a

[2, 4, 5.5, 'hi', (1-2j)]

In [30]:
a.reverse()

In [31]:
a

[(1-2j), 'hi', 5.5, 4, 2]

In [32]:
sample_set={1,"hi",12.5}
sample_set

{1, 12.5, 'hi'}

In [33]:
sample_set.reverse()
sample_set


AttributeError: 'set' object has no attribute 'reverse'

In [34]:
sample_set[2]

TypeError: 'set' object is not subscriptable

In [35]:
list(sample_set)


[1, 12.5, 'hi']

In [36]:
sample_set={1,2,2,2.5}
sample_set


{1, 2, 2.5}

In [37]:
sample_set.add(2)

In [38]:
sample_set

{1, 2, 2.5}

In [39]:
sample_set(3)
sample_set

TypeError: 'set' object is not callable

In [40]:
sample_set.add(3)
sample_set

{1, 2, 2.5, 3}

In [41]:
sample_set.add(1.5)
sample_set

{1, 1.5, 2, 2.5, 3}

In [42]:
sample_set={1,123,43,23,45,67,22,21,3,66,66,0,23,43,1,"hi","fox","a","abc",252,13.5}
sample_set

{0, 1, 123, 13.5, 21, 22, 23, 252, 3, 43, 45, 66, 67, 'a', 'abc', 'fox', 'hi'}

# Add Heterogenous
# Does not allow duplicates
# Cannot access using index
# can add values

In [44]:
#above was for set 


In [45]:
sample_dict={"a",:"alpha",1:"first",2:"second",3:"third",1:"fourth",6:"sixth"}
sample_dict


SyntaxError: invalid syntax (Temp/ipykernel_8784/1915003597.py, line 1)

In [46]:
sample_dict={"a":"alpha",1:"first",2:"second",3:"third",1:"fourth",6:"sixth"}
sample_dict


{'a': 'alpha', 1: 'fourth', 2: 'second', 3: 'third', 6: 'sixth'}

In [47]:
type(sample_dict)

dict

In [48]:
#key value should be unique/values can be duplicated

# Dictionary
# 1. dictionary has key value pair datastructure
# 2. key is unique and values can be duplicated

# Numpy: Package for multidimensional array
# Vector(1D)
# Matrix (2D or 1D)


In [50]:
# Create array
import numpy as np

In [51]:
sample=[6,7,8]
np.array(sample)

array([6, 7, 8])

In [52]:
np.arrange(10,32)


AttributeError: module 'numpy' has no attribute 'arrange'

In [53]:
np.arange(10,32)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [54]:
# step size 1 if not specified

In [55]:
np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [56]:
#by default float

In [57]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

In [58]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.eye(5,dtype=int) #eye for identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [61]:
np.random.rand(2,4) #random no between 0 and 1

array([[0.93798032, 0.52524241, 0.70935945, 0.48816526],
       [0.54172502, 0.85032287, 0.6014037 , 0.78964047]])

In [62]:
np.random.randn(2,4)

array([[ 0.9777036 , -0.39185502,  0.01674284, -0.67289657],
       [-0.17173318,  1.26700282, -1.25417744, -0.14370737]])

In [63]:
np.random.randint(0,10,5)

array([3, 3, 7, 7, 4])

In [64]:
np.random.randint(15,200,20)

array([146, 118, 174, 167, 169, 148,  95, 108,  74,  21, 133,  82, 121,
       131,  30,  97,  83, 110,  54, 157])

In [65]:
np.random,randint(25,60,100)

NameError: name 'randint' is not defined

In [66]:
np.random.randint(25,60,100)

array([34, 39, 55, 54, 45, 57, 39, 38, 39, 29, 44, 52, 49, 29, 26, 40, 40,
       45, 38, 51, 56, 26, 54, 38, 32, 27, 36, 40, 35, 30, 42, 31, 48, 30,
       55, 50, 41, 35, 44, 50, 49, 49, 48, 47, 40, 27, 42, 32, 27, 49, 25,
       29, 59, 58, 40, 27, 37, 59, 27, 26, 55, 49, 41, 28, 54, 44, 56, 37,
       32, 52, 31, 41, 34, 39, 47, 36, 39, 33, 50, 53, 29, 55, 48, 41, 39,
       27, 58, 28, 34, 54, 58, 32, 44, 42, 31, 25, 51, 47, 25, 54])